// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC__90eega35RZkQvQ-D2w36IBvuut_U2c',
    appId: '1:172277128360:web:13bb5cd22463d1a3eab69d',
    messagingSenderId: '172277128360',
    projectId: 'city-car-park-e29de',
    authDomain: 'city-car-park-e29de.firebaseapp.com',
    storageBucket: 'city-car-park-e29de.appspot.com',
    measurementId: 'G-TZ63S1V8QZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUpmobf1GU3bRi1ZkNO29VG5gPa57Cndk',
    appId: '1:172277128360:android:018fd989295118e5eab69d',
    messagingSenderId: '172277128360',
    projectId: 'city-car-park-e29de',
    storageBucket: 'city-car-park-e29de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClSBx-daRIgsFQIwZFZJHDEhggghxF3k0',
    appId: '1:172277128360:ios:cdb56dc3ae808a4ceab69d',
    messagingSenderId: '172277128360',
    projectId: 'city-car-park-e29de',
    storageBucket: 'city-car-park-e29de.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClSBx-daRIgsFQIwZFZJHDEhggghxF3k0',
    appId: '1:172277128360:ios:cdb56dc3ae808a4ceab69d',
    messagingSenderId: '172277128360',
    projectId: 'city-car-park-e29de',
    storageBucket: 'city-car-park-e29de.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC__90eega35RZkQvQ-D2w36IBvuut_U2c',
    appId: '1:172277128360:web:88fb1058aaa2b3f1eab69d',
    messagingSenderId: '172277128360',
    projectId: 'city-car-park-e29de',
    authDomain: 'city-car-park-e29de.firebaseapp.com',
    storageBucket: 'city-car-park-e29de.appspot.com',
    measurementId: 'G-FKW6R0D7KD',
  );
}
